# Introduction

Species distribution models (SDMs) are numerical tools that combine observations of species occurrence or abundance at known locations with information on the environmental and/or spatial characteristics of those locations [@elith_etal_2009]. They are widely used as a tool for understanding species spatial ecology and are also known as ecological niche models (ENM) or habitat suitability models or... SDMS link species occurrence or abundance with environmental features of the location, via statistical modelling. According to ecological niche theory, species response curves are unimodal with respect to environmental gradients. 

A wide variety of methods have been used ... 
While a variety of statistical methods have been developed for species distribution modelling, a general problem with most of these habitat modelling approaches is that the estimated response curves can display biologically implausible shapes which do not respect ecological niche theory. This is because species response curves are fit statistically with any assumption or restriction, which sometimes do not respect the ecological niche theory. To better understand species response to environmental changes, SDMs should consider theoretical background such as the ecological niche theory and pursue the unimodality of the response curve with respect to environmental gradients. At this short course you will learn to build SDMs under the ecological niche theory framework. We will use shape-constrained generalized additive models (SC-GAMs) that allow imposing concavity constraints in the linear predictor scale and avoid overfitting. SC-GAMs are based on the same statistical framework as GLMs and GAMs regression methods, but they allow us to incorporate monotonicity and concavity shape-constraints in the component functions of the linear predictor of the GAMs. Imposing concavity constraints should be an effective alternative to fitting nonsymmetric parametric response curves, while retaining the unimodality constraint, required by ecological niche theory, for direct variables and limiting factors.
Reviews of SDM literature include ... 

One of the common problems is that, the fitted models do not agree with the ecological niche theory...  

This book provides a tutorial on how to use shape-constrained generalized additive models to build SDMs. It is organised following the key steps in good modeling practice of SDMs [@elith_etal_2009]. First, presence data of a selected species are downloaded from GBIF/OBIS global public datasets and pseudo-absence data are created. Then, environmental data are downloaded from public repositories and extracted at each of the presence/pseudo-absence data points. Based on this dataset, an exploratory analysis is conducted to help deciding on the best modelling approach. The model is fitted to the dataset and the quality of the fit and the realism of the fitted response function are evaluated. After selecting a threshold to transform the continuous probability predictions into binary responses, the model is validated using a k-fold approach. Finally, the predicted maps are generated for visualization.      

