---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Prediction and maps

predict from fitted models and produce maps

### Loading required libraries

```{r, eval=F}

library(rgdal)
library(ggplot2)
library(dplyr)
library(fields) #imageplot
library(maps) #map world
library(raster)
library(RColorBrewer)#color palette
library(tidyverse)
library(rstudioapi)
```

# Projection

```{r, eval=F}

# location of script
setwd(dirname(getSourceEditorContext()$path))

#load PA data
load(file.path ("data", "outputs_for_modelling", "PAdata_with_env.Rdata"))

#Load raster stack containing all variables

load("data/env/env_dataframe.Rdata")

#remove positive bathy
env_dataframe<-subset(env_dataframe,BO_bathymean<0)

#Load SC-GAM model

load(file.path("models", "model.Rdata"))

# predicting 
predict <- predict(model,newdata=env_dataframe,type ="response",se.fit=T)         
env_dataframe$fit<-predict$fit
env_dataframe$se.fit<-predict$se.fit

# predicting model without bathymetry
env_dataframe2<-env_dataframe
predict <- predict(model_nobathy,newdata=env_dataframe2,type ="response",se.fit=T)         
env_dataframe2$fit<-predict$fit
env_dataframe2$se.fit<-predict$se.fit

```


# Mapping

```{r, eval=F}
p11<-ggplot()+geom_raster(data=subset(env_dataframe),aes(x,y,fill=fit))+scale_fill_gradient2(low="blue", mid="orange",high="red",midpoint = 0.5) +ggtitle("with bathy concave")+ geom_point(data=subset(data,occurrenceStatus==1),aes(LON,LAT),col=1,size=0.3)     

p12<-ggplot()+geom_raster(data=subset(env_dataframe2),aes(x,y,fill=fit))+scale_fill_gradient2(low="blue", mid="orange",high="red",midpoint = 0.5)+ggtitle("without bathy")+ geom_point(data=subset(data,occurrenceStatus==1),aes(LON,LAT),col=1,size=0.3)       

grid.arrange(p11,p12,nrow=1)


```

