---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Libraries

Load libraries that will be used

```{r}
library("scam")
```

Note that all the libraries must be installed. If some library is not installed, run: 

```{r}
install.packages("scam")
```

#NOTA INTERNA: eta zerbait horrela idazten badugu: 

List of required packages to follow this tutorial
```{r}
requiredPackages <- c(
  #GENERAL USE LIBRARIES --------#
  "here", # Library for reproducible workflow
  "rstudioapi",  # Library for reproducible workflow
  "maptools", #plotting world map
  "ggplot2", #for plotting
  
  #Chapter 3 Presence-absence data --------#
  "robis", # Specific library to get the occurrence data
  "rgbif",# Specific library to get the occurrence data
  "CoordinateCleaner", #to remove outlier
  "rgdal", # to work with Spatial data
  "sf", # to work with spatial data (shapefiles)
  "data.table", #for reading data,
  "dplyr", #for reading data,
  "tidyr", #for reading data,
  
  #Chapter 4 Environmental data --------#
  "raster", #to work with spatial data
  
  #Chapter 5 Prepare final dataset --------#
  
  #Chapter 6 Shape Constrained-Generalized Additive Models --------#
  "scam" #to build SC-GAMs models
  )

```

Function to install packages in case is need and load all required packages
```{r}
#Function to install the required packages that are not in your system and load all the required packages
install_load_function <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

install_load_function(requiredPackages)
```

